### ISSUE TITLE
Discovered again?

### ISSUE THREAD

**Issue by dennidoubles** [arjenbos/ha-postnl#13] opened 2024-01-05 19:06 UTC
I received a discovered device in HA:

![Screenshot_20240105_200158_Home Assistant](https://github.com/arjenbos/ha-postnl/assets/71798417/5f24ac0d-3dd4-4694-b9a4-aef9ce8a509c)

Are you aware of this and why is this, Inhad it already installed and working?

**Comment by arjenbos** [comment] 2024-01-06 11:49
Hi @dennidoubles ,

This is really odd, I didn't add any support for discovery. Which version of HA are you using? Maybe there is an issue on the backlog of HA which is related.

**Comment by dennidoubles** [comment] 2024-01-07 00:21
Running 2024.1
Will check the log if I can find anything.
Strange, right?

**Comment by dennidoubles** [comment] 2024-01-08 14:17
Well, I reconfigured and it is working again. Still strange it got discovered again and needed a re-config, I've heard it also from others. Thanks anyway!

**Comment by arjenbos** [comment] 2024-01-16 08:50
This is really odd, since I do not do anything other than following the guides from HA I do not think it's the integration, but HA that does this strange behaviour. I will close this issue for now, but if it happens again then I will re-open it.

**Comment by dennidoubles** [comment] 2024-01-17 13:48
Well, another discovered notification came in today Arjen:

![image](https://github.com/arjenbos/ha-postnl/assets/71798417/1e1ff1a7-a73f-4670-8275-db62476038f9)

Normally I could just ignore it, but the result is that my card isn't working anymore:

![image](https://github.com/arjenbos/ha-postnl/assets/71798417/c7f63256-fbb9-4884-b248-d6663c8c90a5)

**Comment by stijnb1234** [comment] 2024-01-17 16:11
> Well, another discovered notification came in today Arjen:
> 
> ![image](https://private-user-images.githubusercontent.com/71798417/297398741-1e1ff1a7-a73f-4670-8275-db62476038f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDgxOTEsIm5iZiI6MTcwNTUwNzg5MSwicGF0aCI6Ii83MTc5ODQxNy8yOTczOTg3NDEtMWUxZmYxYTctYTczZi00NjcwLTgyNzUtZGI2MjQ3NjAzOGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE2MTEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMzM4Mjk4MGI0NjFiYjIwYjAxZjdiNjI5M2Y4MTJjMGI2NGNkNDVkZGE4Njk1YTRkODgyOTFmYzA0YjlhYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7xaGf1_R703Hzlh6Ro5wfnJwxaMito7nxs3DyX5gpa8)
> 
> Normally I could just ignore it, but the result is that my card isn't working anymore:
> 
> ![image](https://private-user-images.githubusercontent.com/71798417/297398863-c7f63256-fbb9-4884-b248-d6663c8c90a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDgxOTEsIm5iZiI6MTcwNTUwNzg5MSwicGF0aCI6Ii83MTc5ODQxNy8yOTczOTg4NjMtYzdmNjMyNTYtZmJiOS00ODg0LWIyNDgtZDY2NjNjOGM5MGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE2MTEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ODU4MDUwMzk1MmI2N2MwYjFlOTAyYmFmOGNlODhiNDFiN2NlZmI5M2JiMmJlZGEwOGY5ZjdlY2YwYWY2NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hlBBjclqmnsDVbD3To4Fyqu-EfB69xTKycam9-uHHgc)
> 
> I work with version 1.2.0 and the following:
> 
> ![image](https://private-user-images.githubusercontent.com/71798417/297399558-3938c977-660b-430d-925e-3db624bfbeb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDgxOTEsIm5iZiI6MTcwNTUwNzg5MSwicGF0aCI6Ii83MTc5ODQxNy8yOTczOTk1NTgtMzkzOGM5NzctNjYwYi00MzBkLTkyNWUtM2RiNjI0YmZiZWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE2MTEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlN2RmYTczYzg5NmY5MjM0OTFlY2NkZTVjNWMwZmI2MTc1NTE4NGMwM2VhYjBkMGJhNWI5YWQ1M2RkYmFkZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kAQ9SnKr1Pj5CneUlweVeKtdS4hYLKgUyBPBH5wq1ss)

Same for me

**Comment by stijnb1234** [comment] 2024-01-17 16:12
![image](https://github.com/arjenbos/ha-postnl/assets/27051051/ac607477-8614-47a8-ba1e-58204422529f)
Maybe this is helpful.

**Comment by arjenbos** [comment] 2024-01-18 10:26
This certainly helps; I will try to see if I can reproduce it.

**Comment by arjenbos** [comment] 2024-01-18 12:59
I tested a couple of things. I am not a experienced Python developer, for me this is a hobby. I may do some strange things in my code that are against the principles of Python. So, if people see some strange code in my upcoming changes, please create a PR 😄 .

It's a combination of things that's happening:
1. In the error log you see that PostNL returned a `500 Internal Server Error`. This indicates that their API is broken. That's something I would like to solve, but can't 😅 .
2. That your Lovelace card isn't working is intended behavior if I follow examples from [official integrations](https://github.com/search?q=repo%3Ahome-assistant%2Fcore%20UpdateFailed&type=code). If data isn't returned by external API, then the integration must throw an `UpdateFailed` exception. Due to this exception, the entity is unavailable.
3. Handling exceptions isn't done properly in the integration. Due to this it broke completely.
4. The lovelace isn't able to handle an entity which is unavailable, due to this you see the error `cannot convert undefined or null to object` in the lovelace. This error is raised in Javascript/Typescript.
5. I cannot reproduce the `Discovery` part. The integration doesn't support this at all and I do not know where to start.

I made some changes and I am kindly asking you if you can test it.
1. The integration now catches more exceptions. Hopefully this will make sure that the integration will try again after it broke down.
2. I made a small change in getting the data. If a package is delivered, then I do not call `jouw.postnl.nl` anymore. This will reduce the number of calls with a lot. For me this went down from 40 to 1. And, 0 if I do not an incoming package.

The changes can be inspected in the linked PR. I will merge PR into the main branch. Please checkout this branch via HACS.

**Comment by AarvdH** [comment] 2024-01-18 16:04
It's not really a discovery. I have the same thing, but it happens if a restore a backup.  It says two things, " Discovered "and " Reconfigure "  So I have this with your PostNL integration but also with my FritzBox smarthome integration, Then it loses a repeater, says, Discovered, and the same reconfigure, I only must put in the password of that repeater, and all is fine again.  Maybe it helps you to find what is happening.

**Comment by dennidoubles** [comment] 2024-01-23 16:09
One week later, I experienced it again today.

![image](https://github.com/arjenbos/ha-postnl/assets/71798417/b8c60e65-a3f4-4301-9f0b-c4ab8aa44065)

If I can help you with more info, just let me know. I don't see anything in my logs, which is even more strange ...

**Comment by arjenbos** [comment] 2024-01-23 16:18
> One week later, I experienced it again today.
> 
> ![image](https://private-user-images.githubusercontent.com/71798417/299013305-b8c60e65-a3f4-4301-9f0b-c4ab8aa44065.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjY4NzksIm5iZiI6MTcwNjAyNjU3OSwicGF0aCI6Ii83MTc5ODQxNy8yOTkwMTMzMDUtYjhjNjBlNjUtYTNmNC00MzAxLTlmMGItYzRhYjhhYTQ0MDY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE2MTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyNzYxZDgyZjdlYTlmNmIxNGE4NGY2ZDk0ZTNjY2Q3MmMyMzZkOTI2ZjViNWJiOWZiOWE4ZDE1Y2U5YWMxYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vpNauBY_if3N-gAsiEUKTUtawNkNSKcTO5b44_yhXEc)
> 
> If I can help you with more info, just let me know. I don't see anything in my logs, which is even more strange ...

Could you please check if you have multiple credentials (`/config/application_credentials`) for the PostNL integrations?

**Comment by FeikoJoosten** [comment] 2024-01-24 09:36
I'm pretty sure that it's not really discovering the integration, but that it's failing to connect to the API causing someone to have to reconfigure the integration before it works again. I think that it's caused by the authentication token being expired causing the integration to fail to connect to the post nl servers. 

For me it seems that I have to reconfigure weekly, which would somewhat match with an expiration date for these kind of tokens. 
@arjenbos I'm not sure about the post nl api, but normally if the API returns a refresh token, that token should be used to create a new authentication token. 

Regarding your question for the application_credentials. This is what's stored for me:
```json
{
    "id": "postnl",
    "domain": "postnl",
    "client_id": "-",
    "client_secret": "-",
    "name": "HomeAssistant PostNL"
}
```

**Comment by stijnb1234** [comment] 2024-01-24 09:41
> I'm pretty sure that it's not really discovering the integration, but that it's failing to connect to the API causing someone to have to reconfigure the integration before it works again. I think that it's caused by the authentication token being expired causing the integration to fail to connect to the post nl servers.
> 
> For me it seems that I have to reconfigure weekly, which would somewhat match with an expiration date for these kind of tokens. @arjenbos I'm not sure about the post nl api, but normally if the API returns a refresh token, that token should be used to create a new authentication token.
> 
> Regarding your question for the application_credentials. This is what's stored for me:
> 
> ```json
> {
>     "id": "postnl",
>     "domain": "postnl",
>     "client_id": "-",
>     "client_secret": "-",
>     "name": "HomeAssistant PostNL"
> }
> ```

Yup, it's not a discovery, but it gives an error and then HomeAssistants decides it should be reconfigured.

**Comment by arjenbos** [comment] 2024-01-24 10:04
> I'm pretty sure that it's not really discovering the integration, but that it's failing to connect to the API causing someone to have to reconfigure the integration before it works again. I think that it's caused by the authentication token being expired causing the integration to fail to connect to the post nl servers.
> 
> For me it seems that I have to reconfigure weekly, which would somewhat match with an expiration date for these kind of tokens. @arjenbos I'm not sure about the post nl api, but normally if the API returns a refresh token, that token should be used to create a new authentication token.
> 
> Regarding your question for the application_credentials. This is what's stored for me:
> 
> ```json
> {
>     "id": "postnl",
>     "domain": "postnl",
>     "client_id": "-",
>     "client_secret": "-",
>     "name": "HomeAssistant PostNL"
> }
> ```

That's indeed default oAuth2 behaviour which is developed and controlled by [Home Assistant core](https://developers.home-assistant.io/docs/core/platform/application_credentials/). I will have another look and see if something goes wrong in combination with the access_token and refresh_token.

**Comment by arjenbos** [comment] 2024-01-25 07:36
I think I found it. This behaviour is initiated due to a `ConfigEntryAuthFailed` exception. I cannot reproduce why you guys hit this exception.

The exception was thrown when the API returned an HTTP response status code between 400 and 500. I changed the code in the `main` branch to throw a HomeAssistantError exception instead and I added some debug logging. Hopefully we can figure out why the PostNL API returns an error code between the 400 and 500.

@stijnb1234 @FeikoJoosten could you please pull the latest version of the main branch and enable debug logging?

**Comment by stijnb1234** [comment] 2024-01-25 09:25
> I think I found it. This behaviour is initiated due to a `ConfigEntryAuthFailed` exception. I cannot reproduce why you guys hit this exception.
> 
> The exception was thrown when the API returned an HTTP response status code between 400 and 500. I changed the code in the `main` branch to throw a HomeAssistantError exception instead and I added some debug logging. Hopefully we can figure out why the PostNL API returns an error code between the 400 and 500.
> 
> @stijnb1234 @FeikoJoosten could you please pull the latest version of the main branch and enable debug logging?

Installed the main branch version again, will let you know when I have anything.

**Comment by FeikoJoosten** [comment] 2024-01-25 09:43
Same here!

**Comment by dennidoubles** [comment] 2024-01-25 14:58
Don't understand what to do next, so I guess I'll wait for your feedback

**Comment by FeikoJoosten** [comment] 2024-02-08 07:56
So far no issues on my end. Seems to work like a charm

**Comment by dennidoubles** [comment] 2024-02-11 00:46
Is the new version a fix for this issue?
That would great work!

**Comment by stijnb1234** [comment] 2024-02-11 09:52
> No feedback received, so I assume it's fixed?

Same for me, no issues.

**Comment by arjenbos** [comment] 2024-02-11 10:24
Nice, I the latest release includes the fixes.

**Closed by arjenbos** 2024-02-11 10:24 UTC
